SYMBOL = "BTC/USD"

TRADE_AMOUNT_USD = 20
MAX_POSITION_USD = 100

FAST_MA = 10
SLOW_MA = 30
RSI_PERIOD = 14
RSI_BUY_THRESHOLD = 70

CHECK_INTERVAL_SECONDS = 60
LIVE_TIMEFRAME = "5Min"

STOP_LOSS_PERCENT = 0.02
TAKE_PROFIT_PERCENT = 0.04

DATABASE_PATH = "trading_bot.db"

BACKTEST_STARTING_CAPITAL = 1000.0
BACKTEST_LOOKBACK_DAYS = 30
BACKTEST_TIMEFRAME = "5Min"
BACKTEST_FEE_PERCENT = 0.001
BACKTEST_SLIPPAGE_PERCENT = 0.0005
BACKTEST_SAVE_TRADES_CSV = True
BACKTEST_ZERO_COST_DIAGNOSTIC = False
