SYMBOL = "BTC/USD"

DATABASE_PATH = "trading_bot.db"

BACKTEST_STARTING_CAPITAL = 1000.0
BACKTEST_LOOKBACK_DAYS = 30
# Assumed Alpaca crypto taker fee for market orders at low volume; update if fee tier changes.
BACKTEST_FEE_PERCENT = 0.0025
BACKTEST_SLIPPAGE_PERCENT = 0.0005
BACKTEST_SAVE_TRADES_CSV = True
BACKTEST_ZERO_COST_DIAGNOSTIC = False
